<?php 
/**
 * Febin_Employee extension
 * 
 * NOTICE OF LICENSE
 * 
 * This source file is subject to the MIT License
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/mit-license.php
 * 
 * @category       Febin
 * @package        Febin_Employee
 * @copyright      Copyright (c) 2015
 * @license        http://opensource.org/licenses/mit-license.php MIT License
 */
/**
 * Employee list template
 *
 * @category    Febin
 * @package     Febin_Employee
 * @author      Febin Thomas
 */
?>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<?php $_employees = $this->getEmployees(); ?>
<div class="page-title employee-title">
    <h1><?php echo Mage::helper('febin_employee')->__('Employee') ?></h1>
</div>
<?php if ($_employees->getSize() > 0) :?>
    <?php echo $this->getPagerHtml(); ?>
    <div class="employee-list-container">
    <?php foreach ($_employees as $_employee) : ?>
        <div class="employee-list-item">
            <?php echo $_employee->getEmployeeName();?>
<br />
        </div>
    <?php endforeach;?>
    </div>
    <?php echo $this->getPagerHtml(); ?>
<?php else : ?>
    <?php echo Mage::helper('febin_employee')->__('There are no employee at this moment');?>
<?php endif;?>
