<?php 
/**
 * Febin_Employee extension
 * 
 * NOTICE OF LICENSE
 * 
 * This source file is subject to the MIT License
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/mit-license.php
 * 
 * @category       Febin
 * @package        Febin_Employee
 * @copyright      Copyright (c) 2015
 * @license        http://opensource.org/licenses/mit-license.php MIT License
 */
/**
 * Blog list template
 *
 * @category    Febin
 * @package     Febin_Employee
 * @author      Febin Thomas
 */
?>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<?php $_blogs = $this->getBlogs(); ?>
<div class="page-title blog-title">
    <h1><?php echo Mage::helper('febin_employee')->__('Blog') ?></h1>
</div>
<?php if ($_blogs->getSize() > 0) :?>
    <?php echo $this->getPagerHtml(); ?>
    <div class="blog-list-container">
    <?php foreach ($_blogs as $_blog) : ?>
        <div class="blog-list-item">
            <a href="<?php echo $_blog->getBlogUrl()?>">
                <?php echo $_blog->getBlogTitile();?>
            </a><br />
        </div>
    <?php endforeach;?>
    </div>
    <?php echo $this->getPagerHtml(); ?>
<?php else : ?>
    <?php echo Mage::helper('febin_employee')->__('There are no blog at this moment');?>
<?php endif;?>
