<?php
/**
 * Febin_Employee extension
 * 
 * NOTICE OF LICENSE
 * 
 * This source file is subject to the MIT License
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/mit-license.php
 * 
 * @category       Febin
 * @package        Febin_Employee
 * @copyright      Copyright (c) 2015
 * @license        http://opensource.org/licenses/mit-license.php MIT License
 */
/**
 * Blog view template
 *
 * @category    Febin
 * @package     Febin_Employee
 * @author      Febin Thomas
 */
?>
<?php $_blog = $this->getCurrentBlog();?>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<div class="page-title blog-title">
    <h1><?php echo $_blog->getBlogTitile(); ?></h1>
</div>
<div class="blog-view">
    <div class="blog-blog_titile">
        <?php echo Mage::helper('febin_employee')->__('Blog Titile');?>:<?php echo $_blog->getBlogTitile();?>

    </div>
    <div class="blog-blog_content">
        <?php echo Mage::helper('febin_employee')->__('Blog content');?>:<?php echo $_blog->getBlogContent();?>

    </div>

</div>
